import { useParams } from "react-router-dom"
const events = [
  {
    _id: "1",
    title: "Fundraiser",
    photo: null,
    description: "Fundraiser for Climate",
    dateStart: new Date("2021-11-02T10:00:00.000Z"),
    dateEnd: new Date("2021-11-04T12:00:00.000Z"),
    address: "Geschwister-Scholl-Straße",
    city: "Berlin",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "public",
    link: "",
    tags: ["#fundraiser", "#climate-change"],
    annouce: false,
    zoom: 18,
    location: "Library",
    organizer: { _id: "1", firstName: "Victor", lastName: "Isidoro" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "2",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-02T10:00:00.000Z"),
    dateEnd: new Date("2021-11-04T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "3",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-04T10:00:00.000Z"),
    dateEnd: new Date("2021-11-04T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "4",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-06T10:00:00.000Z"),
    dateEnd: new Date("2021-11-07T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#health", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "5",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-07T10:00:00.000Z"),
    dateEnd: new Date("2021-11-07T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "6",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-06T10:00:00.000Z"),
    dateEnd: new Date("2021-11-06T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "7",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-08T10:00:00.000Z"),
    dateEnd: new Date("2021-11-08T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "8",
    title: "Halloween",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-10-31T10:00:00.000Z"),
    dateEnd: new Date("2021-11-01T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
  {
    _id: "9",
    title: "Conference",
    photo: null,
    description: "Conference on Food Shortage",
    dateStart: new Date("2021-11-02T10:00:00.000Z"),
    dateEnd: new Date("2021-11-04T12:00:00.000Z"),
    address: "",
    city: "",
    geoLocation: {
      lat: 52.5205888,
      lng: 13.3912322,
    },
    type: "online",
    link: "https://www.techonthenet.com/js/string_match.php",
    tags: ["#food", "#speaker", "#online"],
    annouce: false,
    zoom: 18,
    location: "",
    organizer: { _id: "1", firstName: "Sasmitha", lastName: "Kumar" },
    interested: [],
    going: [],
    canceled: false,
  },
]

const Event = () => {
  const { id } = useParams()
  const [event] = events.filter((event) => event._id === id)
  console.log(event)
  return <div>Event id {event._id}</div>
}
export default Event
